name: deploy

on:
  push:
    branches: [master] # 1.这里是你当前主分支的名字,我这里是main,你的可能是master
    paths-ignore:
      - README.md ## 2.表示该文件更新不会触发Github Actions部署,自行配置即可

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install # 安装依赖
      - run: npm run build # 打包

  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with: 
           publish_dir: ./doc # 3.打包后文件的输出目录(根据你自己的项目情况而定)
